//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository_UnitOfWork_DAL.EF_Data_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommitteeMember
    {
        public int CommitteeMemberId { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public Nullable<int> CommitteeId { get; set; }
        public Nullable<int> AgencyId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual Committee Committee { get; set; }
    }
}
