//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository_UnitOfWork_DAL.EF_Data_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionId { get; set; }
        public Nullable<int> UserPaymentMethodId { get; set; }
        public string CardHolderName { get; set; }
        public string CardNumber { get; set; }
        public Nullable<System.DateTime> CardExpiryDate { get; set; }
        public string CardSecurityCode { get; set; }
        public string TransactionDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual UserPaymentMethod UserPaymentMethod { get; set; }
    }
}
