//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository_UnitOfWork_DAL.EF_Data_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAgency
    {
        public int UserAgencyId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> AgencyId { get; set; }
        public string AgencyName { get; set; }
        public string Address { get; set; }
        public string ContactPersonName { get; set; }
        public string ContactPersonDesignation { get; set; }
        public string ContactPersonNationality { get; set; }
        public string ContactPersonNIDNumber { get; set; }
        public Nullable<System.DateTime> ContactPersonBirthDate { get; set; }
        public string ContactPersonPermanentAddress { get; set; }
        public string TradeLicenseNumber { get; set; }
        public string MOCATRegistrationNumber { get; set; }
        public string TelephoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string MobileNumber { get; set; }
        public string Website { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual User User { get; set; }
    }
}
